choco upgrade chocolatey -y
choco install git -y
choco install nodejs-lts -y
choco install visualstudio2019community -y
choco install visualstudio2019-workload-azure -y
choco install visualstudio2019-workload-manageddesktop -y
choco install visualstudio2019-workload-netcoretools -y
choco install visualstudio2019-workload-node -y
choco install vscode -y
choco install vscode-prettier -y
choco install vscode-eslint -y
choco install sql-server-management-studio -y