choco install -y googlechrome 
choco install -y nodejs.install 
choco install -y vlc 
choco install -y visualstudiocode
choco install -y visualstudio2017professional 
choco install -y tortoisehg
choco install -y tortoisesvn
choco install -y sourcetree
choco install -y wixtoolset
choco install -y beyondcompare
choco install -y fiddler4
choco install -y baretail
choco install -y vagrant
choco install -y spotify
choco install -y virtualbox